<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>f1e1029d-5b98-491d-803f-457fbed02ffc</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="SendGrid" Version="9.29.3" />
  </ItemGroup>

</Project>
